### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by anuragkh** [excamera/alfalfa#70]
I'm trying to build alfalfa on an EC2 instance (m4.large), [Debian image](https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch) for running the xc-enc example outlined in the Mu repo.

The build fails when running `make`:

```bash
../encoder/libalfalfaencoder.a(encoder.o): In function `Encoder::chroma_mb_best_prediction_mode(VP8Raster::Macroblock const&, VP8Raster::Macroblock&, VP8Raster::Macroblock&, bool) const':
/tmp/mu_example/alfalfa/src/encoder/encode_intra.cc:232: undefined reference to `VP8Raster::Block<8u>::predictors() const'
/tmp/mu_example/alfalfa/src/encoder/encode_intra.cc:233: undefined reference to `VP8Raster::Block<8u>::predictors() const'
../encoder/libalfalfaencoder.a(encoder.o): In function `Encoder::update_macroblock(VP8Raster::Macroblock const&, VP8Raster::Macroblock&, VP8Raster::Macroblock&, Macroblock<InterFrameHeader, InterFrameMacroblockHeader>&, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> const&, Quantizer const&)':
/tmp/mu_example/alfalfa/src/encoder/./../decoder/vp8_raster.hh:91: undefined reference to `VP8Raster::Block<8u>::predictors() const'
/tmp/mu_example/alfalfa/src/encoder/./../decoder/vp8_raster.hh:91: undefined reference to `VP8Raster::Block<8u>::predictors() const'
collect2: error: ld returned 1 exit status
Makefile:601: recipe for target 'xc-enc' failed
```

**Comment by anuragkh** [comment]
The error goes away if I explicitly instantiate the VP8Raster::Block templates at the end of `src/decoder/prediction.cc`:

```cpp
template class VP8Raster::Block<4>;
template class VP8Raster::Block<8>;
template class VP8Raster::Block<16>;
```

**Comment by keithw** [comment]
Hello Anurag,

What version of GCC are you using? I just confirmed it compiles with GCC 6 and GCC 7.

-Keith

**Comment by anuragkh** [comment]
I'm using GCC 5.5.0:

```bash
$ g++ --version
g++ (Debian 5.5.0-8) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by keithw** [comment]
That's probably the problem -- could you please try with a newer GCC? (Alfalfa uses C++14 and I'm not sure about GCC5's support in any event.)

**Comment by anuragkh** [comment]
I updated to gcc 6.3.0, still see the same issue.

```bash
$ g++ --version
g++ (Debian 6.3.0-18) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I follow the steps outlined in the Mu repo:

```bash
mkdir -p /tmp/mu_example/alfalfa
cd /tmp/mu_example
git clone https://github.com/excamera/alfalfa
cd alfalfa
./autogen.sh
./configure --enable-all-static
make
```
And see this error message for the final make step:

```bash
...
make[3]: Entering directory '/tmp/mu_example/alfalfa/src/frontend'
  CXX      vp8decode.o
  CXXLD    vp8decode
  CXX      xc-enc.o
  CXXLD    xc-enc
../encoder/libalfalfaencoder.a(encoder.o): In function `Encoder::chroma_mb_best_prediction_mode(VP8Raster::Macroblock const&, VP8Raster::Macroblock&, VP8Raster::Macroblock&, bool) const':
/tmp/mu_example/alfalfa/src/encoder/encode_intra.cc:232: undefined reference to `VP8Raster::Block<8u>::predictors() const'
/tmp/mu_example/alfalfa/src/encoder/encode_intra.cc:233: undefined reference to `VP8Raster::Block<8u>::predictors() const'
../encoder/libalfalfaencoder.a(encoder.o): In function `Encoder::update_macroblock(VP8Raster::Macroblock const&, VP8Raster::Macroblock&, VP8Raster::Macroblock&, Macroblock<InterFrameHeader, InterFrameMacroblockHeader>&, Macroblock<InterFrameHeader, InterFrameMacroblockHeader> const&, Quantizer const&)':
/tmp/mu_example/alfalfa/src/encoder/./../decoder/vp8_raster.hh:91: undefined reference to `VP8Raster::Block<8u>::predictors() const'
/tmp/mu_example/alfalfa/src/encoder/./../decoder/vp8_raster.hh:91: undefined reference to `VP8Raster::Block<8u>::predictors() const'
collect2: error: ld returned 1 exit status
Makefile:601: recipe for target 'xc-enc' failed
make[3]: *** [xc-enc] Error 1
make[3]: Leaving directory '/tmp/mu_example/alfalfa/src/frontend'
Makefile:376: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/mu_example/alfalfa/src'
Makefile:424: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/mu_example/alfalfa'
Makefile:356: recipe for target 'all' failed
make: *** [all] Error 2
```

Also, if I add the three lines above, that resolves the build issue for both gcc versions.

**Comment by keithw** [comment]
FWIW, it does work in Travis-CI with GCC 6.3.0 (as well as locally). (See https://travis-ci.org/excamera/alfalfa). I think to debug we would probably need the full build log, compiled with "make V=1" to see all the command lines.

**Comment by anuragkh** [comment]
Attaching the build log here. 
[build.log](https://github.com/excamera/alfalfa/files/1735653/build.log)

**Comment by keithw** [comment]
Ok, the problem here is that the Ubuntu GCC is compiled to use `-D_FORTIFY_SOURCE=2` (which causes the template to be instantiated), which is why this works in continuous integration with GCC 6 and not on your Debian VM. We'll take a pull request to explicitly instantiate the template if you want to send one.
